#!/bin/sh
# change to script's directory
cd `dirname "$0"`

# now into the target dir
cd planet_sage

# this calls the update script (via crontab!) and files end up in "output"
python ../planet-2.0/planet.py config.ini 1> ../log/update.out 2> ../log/update.error
